name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: build state_duration
      run: python3 state_duration.py
      if: ${{ always() }}

    - name: build state_change
      run: python3 state_change.py
      if: ${{ always() }}

    - name: build to_datetime
      run: python3 to_datetime.py
      if: ${{ always() }}

    - name: build timestamp_df.py
      run: python3 timestamp_df.py
      if: ${{ always() }}

    - name: build tuple_test.py
      run: python3 tuple_test.py
      if: ${{ always() }}

    - name: artifact csv
      uses: actions/upload-artifact@v3
      with:
        name: csv
        path: '*.csv'

    - name: artifact png
      uses: actions/upload-artifact@v3
      with:
        name: png
        path: '*.png'

    - name: artifact xlsx
      uses: actions/upload-artifact@v3
      with:
        name: xlsx
        path: '*.xlsx'
